Rebuilding enumerable methods in ruby
Anvi98/Enumerable-Methods-Rebuilt pull request #1
Opened 2021-03-19 19:22 UTC by Maha-Magdy

What we did in this project, my partner and I is to re-create some enumerable methods and add them to the enumerable module. 
The methods that we created are:
#my_each
#my_each_with_index
#my_all?
#my_any?
#my_none?
#my_count
#my_map
#my_inject
, and also we made #my_multiply_els which uses my_inject to multiply all the elements from the array given.

2021-03-20 03:14 UTC, umairarshadbutt requested changes
# Status: REQUIRED CHANGES :warning: :construction: 

Hi @Maha-Magdy and @Anvi98 
Such a remarkable project you made :+1: ! Awesome README :100: !
We, however, do have a few changes to carry out before we proceed.

##

Kindly work on the suggested changes.
- [ ] `#my_each` when a block is given when self is an array returns the array itself after calling the given block once for each element in self
- [ ] `#my_each` when a block is given when self is a range returns the range itself after calling the given block once for each element in self
- [ ] `#my_each_with_index` when a block is given when self is an array returns the array itself after calling the given block once for each element in self
- [ ] `#my_each_with_index` when a block is given when self is a range returns the range itself after calling the given block once for each element in self
- [ ] `#my_all?` when no block or argument is given returns false when one of the collection members are false or nil
- [ ] `#my_all?` when a class is passed as an argument returns true if all of the collection is a member of such class::Integer
- [ ] `#my_all?` when a class is passed as an argument returns true if all of the collection is a member of such class::Numeric
- [ ] `#my_all?` when a class is passed as an argument returns false if any of the collection is not a member of such class
- [ ] `#my_all?` when a Regex is passed as an argument returns true if all of the collection matches the Regex
- [ ] `#my_all?` when a Regex is passed as an argument returns false if any of the collection does not match the Regex
- [ ] `#my_all?` when a pattern other than Regex or a Class is given returns true if all of the collection matches the pattern
- [ ] `#my_all?` when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern
- [ ] `#my_any?` when no block or argument is given returns false if at least one of the collection is not true
- [ ] `#my_any?` when a class is passed as an argument returns true if at least one of the collection is a member of such class::Numeric
- [ ] `#my_any?` when a class is passed as an argument returns true if at least one of the collection is a member of such class::Integer
- [ ] `#my_any?` when a Regex is passed as an argument returns true if any of the collection matches the Regex
- [ ] `#my_any?` when a Regex is passed as an argument returns false if none of the collection matches the Regex
- [ ] `#my_any?` when a pattern other than Regex or a Class is given returns false if none of the collection matches the pattern
- [ ] `#my_any?` when a pattern other than Regex or a Class is given returns true if any of the collection matches the pattern
- [ ] `#my_none?` when no block or argument is given returns true only if none of the collection members is true
- [ ] `#my_none?` when a class is passed as an argument returns true if none of the collection is a member of such class
- [ ] `#my_none?` when a class is passed as an argument returns true if none of the collection is a member of such class::Numeric
- [ ] `#my_none?` when a class is passed as an argument returns false if any of the collection is a member of such class
- [ ] `#my_none?` when a Regex is passed as an argument returns true if none of the collection matches the Regex
- [ ] `#my_none?` when a Regex is passed as an argument returns false if any of the collection matches the Regex
- [ ] `#my_none?` when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
- [ ] `#my_none?` when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern
- [ ] `#my_count` returns the number of items in enum through enumeration
- [ ] `#my_count` returns the number of items in enum through enumeration::range
- [ ] `#my_count` counts the number of elements yielding a true value if a block is given
- [ ] `#my_count` does not mutate the original array
- [ ] `#my_map` returns an Enumerator if no block is given
- [ ] `#my_map` executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.
- [ ] `#my_inject` does not mutate the original array
- [ ] `#my_inject` when a block is given without an initial value combines all elements of enum by applying a binary operation, specified by a block
- [ ] `#my_inject` when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method
- [ ] `#my_inject` when a symbol is specified without an initial value combines each element of the collection by applying the symbol as a named method:range
- [ ] `#my_inject` when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method
- [ ] `#my_inject` when a symbol is specified with an initial value combines each element of the collection by applying the symbol as a named method::range
##
- **When you have made the specified changes, please submit another code review. Thank you!**
##
**If you are stuck at any point or have any questions, let me know by leaving a comment here and mentioning me. I will be happy to help**
HAPPY CODING :computer:
**[Umair Arshad](https://umairarshad.me/)**
[Twitter](https://twitter.com/its_UmairArshad) | [LinkedIn](https://www.linkedin.com/in/umair-arshad-butt/) | [GitHub](https://github.com/umairarshadbutt)

2021-03-23 20:04 UTC, Anvi98 commented
In this new PR, we tried to fix all the observations from the last TSE.  However, we want to highlight something in our code.
we commented this code below in the my_all?, my_any? my_none? enumerable method:

# elsif !param.is_a?(Class) && !param.is_a?(Regexp)
        #   case param
        #     in self
        #       return true
        #   else
        #     return false
        #   end

The reason for that is because we tried to implement the pattern matching with the case statement, and this is in the experimental state. So, to pass the checks, we commented on this code, but if you need to test the full code, you need to uncomment this small part of it.

2021-03-23 20:30 UTC, smcommits commented on enumerable.rb
> +  def my_any?(param = nil)
- [ ] **enumerables #my_any? when no block or argument is given returns false if at least one of the collection is not true**

Case
```
false_array.my_any?
```
```
expected false
            got true
```

2021-03-23 21:00 UTC, smcommits requested changes
# Status: Changes Requested 
## Hello, @Maha-Magdy and @Anvi98! You guys have done a great job. The methods are passing almost all the test cases. But, your methods are still missing some behaviors that are present in the original methods

## Request Changes
**Please note that I have uncommented the code that you suggested and the following cases are still failing**

I have used the following variables for testing the methods. The inline code shows all the use cases of these variables and their respective output. 

```
words = %w[dog door rod blade cat]
false_array = [nil, false, nil, false]
```

#
### Please don't hesitate to contact me on [Slack](https://microverse-students.slack.com/team/U017N7LLZ40) if you need assistance or believe I have overlooked something and made an unfair request.

2021-03-23 21:00 UTC, smcommits commented on enumerable.rb
> +  def my_any?(param = nil)
- [x] **enumerables #my_any? when no block or argument is given returns false if at least one of the collection is not true**

Case
```
false_array.my_any?
```
```
expected false
            got true
```

- [x] **enumerables #my_any? when a pattern other than Regex or a Class is given returns true if any of the collection matches the pattern**

Case
```
words.my_any?('cat')
```
```
expected true
            got false
```

2021-03-23 21:00 UTC, smcommits commented on enumerable.rb
> +  def my_inject(param = nil, symbol_value = nil)
- [x] **enumerables #my_inject raises a "LocalJumpError" when no block or argument is given**

Case
```
array.my_inject
```
```
expected LocalJumpError but nothing was raised
```

2021-03-23 22:37 UTC, rukundoeric requested changes
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯

- ### To Improve 
  - [ ] [MANDATORY] #my_all? when a pattern other than Regex or a Class is given returns false if any of the collection does not match the pattern.
     - Example `[3, 3, 3].my_all?(3)`
       - Expected: `true`
       - Got: `nil`
  - [ ] [MANDATORY] #my_any? when no block or argument is given returns true if at least one of the collection is not false or nil
     - Example `[3, 3, 4].my_any?`
       - Expected: `true`
       - Got: `false`
  - [x] [MANDATORY] #my_none? when a pattern other than Regex or a Class is given returns false only if one of the collection matches the pattern
     - Example `[5, 'nino', 8 , 9].my_none?(5)`
       - Expected: `false`
       - Got: `nil`
  - [x] [MANDATORY] #my_none? when a pattern other than Regex or a Class is given returns true only if none of the collection matches the pattern
     - Example `[2, 'nino', 8 , 9].my_none?(5)`
       - Expected: `true`
       - Got: `nil`
  - [x] [MANDATORY] #my_map executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.
     - Example `[10, 11, 2, 1].my_map(&proc { |num| num > 10 }) { |num| num < 10 }`
       - Expected: `[false, true, false, false]`
       - Got: `[true, false, true, true]`
  - [x] [MANDATORY] Kindly remove all commented codes.     

_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

2021-03-24 16:56 UTC, rukundoeric requested changes
# Status: ♻️ CHANGES REQUIRED ♻️
_Great job guys so far 👏 💯 👍. However, there are few issues we need to address before we move on, please check the comments below._

- ### To Highlight
  - [x] The project is clean. 💯
  - [x] The project follows Git flow. 💯

- ### To Improve  
  - [ ] [MANDATORY] #my_map executes only the proc when both a block and a proc are given and returns a new array with the results of running the proc once for every element in enum.
     - Example `[10, 11, 2, 1].my_map(&proc { |num| num > 10 }) { |num| num < 10 }`
       - Expected: `[false, true, false, false]`
       - Got: `both block arg and actual block given`.

  NOTE: Remember if both proc and block are given. execute proc and ignore block.

_Please make all the required changes before you submit another code review. If you have any problems or concerns, you can reach out to me on Slack: Rukundo Eric 🚀 . I wish you all the very best 🥇_

### _Keep working hard._
### _Happy Coding😃_
-----------------------------------------------------------------------------------------------------------------------------------------
**Regards,
[Rukundo Eric](https://rukundo-eric.herokuapp.com/) ,
[LinkedIn](https://www.linkedin.com/in/rukundo-eric/), 
Slack: Rukundo Eric**

2021-03-24 20:34 UTC, henatan99 approved these changes
# Project Approved 
## Congratulations :100: :partying_face: 
Hey @Maha-Magdy, you did an amazing job. Your enumerable module passes all the spec tests. Well Done!!!!! 
You may now merge the PR and submit the mandatory project completion form. 

If you have any queries, you can reach out to me via:
- [LinkedIn](https://www.linkedin.com/in/henok-mekonnen-2a251613/)
- [Twitter](https://twitter.com/henatan99)
- or Slack by 'Henok Mekonnen Mossissa' 

### Good Luck in your upcoming projects

2021-03-24 20:52 UTC, merged